### ISSUE TITLE
Incompatible or non friendly behavior of -srv and friends

### ISSUE THREAD

**Issue by williamdes** [PennockTech/smtpdane#7]
```
$ smtpdane -show-cert-info -srv -submissions wdes.fr
error resolving SRV "_-submissions._tcp.wdes.fr":
	no results found
```

The generated record makes no sense, I was thinking that submissions and friends would be a sub category
But it turns out that I need to remove `-srv` to use `-submissions` or it will create a very wrong record.

I did end up into this because I first tried -srv and then realised it needed one more, so I just added -submissions and a 🐛 was born

Other than that, thank you so much for considering SRV !

**Comment by philpennock** [comment]
The `-srv` option takes a string argument (see the `-help` output), so you told it that the service to use is "-submissions".

Now, you should be able to use `-srv submissions` and that should have worked well enough, and it doesn't, and _that's_ a bug.

**Comment by philpennock** [comment]
Ah, no, it's not: `-submissions` is a shortcut for `-tls-on-connect -srv submissions` and my quick testing didn't set `-tls-on-connect`.  When I remember that, everything works.

There probably needs to be some better diagnostic handling for when the server speaks TLS-on-connect and we didn't expect it, instead of hanging.

**Comment by philpennock** [comment]
Commit e554c4facc1e05bd160572027f488e30772af100 will protect against this in the future.  I don't currently plan to cut a new release any time soon, we'll see what else is found to be fixed before I do that. :)

**Comment by williamdes** [comment]
Thank you!
