### ISSUE TITLE
Add an option to disable TSLA check ?

### ISSUE THREAD

**Issue by williamdes** [PennockTech/smtpdane#8]
I would like to check SRV records, but in my domain scheme SRV records have different names than MX records.
And the SRV records have no TSLA records. It would be nice to be able to disable TSLA checks for example.

I have TSLA setup only for MX records:
- mx1.provider.tld
- mx2.provider.tld

But SRV have values like:
- imap.provider.tld
- smtp.
- pop3.

Test command: `smtpdane -show-cert-info -submissions wdes.fr`

One last thing, I was thinking `-nocertnames` would shut it up and check TSLA post connect, but it looks like that's not true 🤔

**Comment by philpennock** [comment]
So this tool is `smtpdane`, the whole point is DANE service checking, where DANE fundamentally uses TLSA records to provide the trust anchors.

* <https://datatracker.ietf.org/doc/html/rfc6698>
* <https://datatracker.ietf.org/doc/html/rfc7672>

If we add an option for smtpdane to not check dane, then we'd need to figure out exactly what the scope of this tool becomes.  What is it expected to be here, an SMTP probe for a NAGIOS-compatible system, which can check TLS certs, without requiring DANE?

**Comment by williamdes** [comment]
That is very true !

Maybe I have an alternative way, what if we check that DANE passes after connection using the server side EHLO ?
https://aws.amazon.com/blogs/messaging-and-targeting/debugging-smtp-conversations-part-1-how-to-speak-smtp/

I am not too sure about if this is possible. But one "true way" to identify the server is to use EHLO reply on some setups

https://github.com/PennockTech/smtpdane/blob/a77984bffdb13932b11c471c168a6309c36ccfae/probe.go#L396

-----

TSLA records are difficult to maintain, maybe I will add the values on a provider level setup for imap. and friends but I can not for example ask to clients to add TSLA records to their domain specific imap.clientdomain.tld. They will never ship updates properly. Anyway I avoid giving them imap/smtp/pop3.clientdomain.tld.
I am not even sure a lot of client software will use them. But it's probably more efficient to have them on the MX records because of MTA-STS. That will be used for real by other email servers and monitoring websites like https://stats.dnssec-tools.org/ (it sent me an email when the record got wrong, I never subscribed, that's nice 😄 )

**Comment by philpennock** [comment]
So, what precisely are you looking for this tool to do?  What should it be verifying, and what is the scope?

Note that either the TLS session is setup, with a hostname validated, before SMTP is spoken (TLS-on-connect) or cleartext SMTP is used first, which means that any identity provided in the EHLO response is not safe to use when validating a TLS handshake.

Assuming "C" for Client, "M" for Mallory, "S" for Server, if C sends towards what it thinks is S, then either every piece of the network stack is safe and _there's no need for TLS beyond anonymous TLS without identities_, **or** C needs to make sure that it's not actually talking to M.

```
C -> M: EHLO trusting.victim
M -> C: 250-interceptor.example Hello trusting
M -> C: 250 STARTTLS
```

At this point, I don't think it's appropriate for the Client to start a TLS handshake and accept a server hostname of `interceptor.example`.  This is the whole point of DANE, or MTA-STS.

I am no longer really involved in the mail-server world, I'm not going to start making all-purpose tools for others to use in every conceivable situation.  This tool is for DANE verification.  If it's "almost enough" for a situation which isn't DANE, then I think the right solution is to fork it, rename to something more appropriate, and develop the features you need.  I think this is probably the right path forward here.

**Comment by williamdes** [comment]
Hello,

Thank you for this answer

>So, what precisely are you looking for this tool to do? What should it be verifying, and what is the scope?
I just wanted to validate SRV records and the end email server. But I agree that indeed what I wanted to have is not possible. Adding TSLA records would definitely be the right way. 

I will consider this

My goal is to add some commands to status.datacenters.network using this tool

I successfully added checks using your tool, so that's cool! 
https://github.com/datacenters-network/status/blob/4dcd33a134ace6a9234bd50f7c7ae0165353a00d/vigil.cfg#L172
